{% set name = "flake8-no-implicit-concat" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-no-implicit-concat-{{ version }}.tar.gz
  sha256: ba7f156b5f0e452b8641ec83075bf749e6d18d84dbb5b7a7466f7825c71270c4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flake8
    - more-itertools
    - python >=3.6
    - typing

test:
  imports:
    - flake8_no_implicit_concat
  commands:
    - pip check
    - flake8 --version | grep no_implicit_concat
  requires:
    - flake8
    - pip
    - m2-grep  # [win]

about:
  home: https://github.com/10sr/flake8-no-implicit-concat
  summary: Flake8 plugin that forbids implicit str/bytes literal concatenations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
