{% set name = "flake8-no-implicit-concat" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-no-implicit-concat-{{ version }}.tar.gz
  sha256: b68ff39c5620b0c9fd412c22e6dd98e56ca255eb9cc007135dbc26033dc5e07d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flake8
    - more-itertools
    - python >=3.6
    - typing

test:
  imports:
    - flake8_no_implicit_concat
  commands:
    - pip check
    - flake8 --version | grep no_implicit_concat
  requires:
    - flake8
    - pip
    - m2-grep  # [win]

about:
  home: https://github.com/10sr/flake8-no-implicit-concat
  summary: Flake8 plugin that forbids implicit str/bytes literal concatenations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
