{% set name = "flake8-no-implicit-concat" %}
{% set version = "0.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 41519e710ba725ce1749e0da46cb5b27d9ed407d1da4e48357f60178e8387462

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flake8
    - more-itertools
    - python >=3.6
    - typing

test:
  imports:
    - flake8_no_implicit_concat
  commands:
    - pip check
    - flake8 --version | grep no-implicit-concat
  requires:
    - flake8
    - pip
    - m2-grep  # [win]

about:
  home: https://github.com/10sr/flake8-no-implicit-concat
  summary: Flake8 plugin that forbids implicit str/bytes literal concatenations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
