{% set name = "flake8-no-implicit-concat" %}
{% set version = "0.3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8472f2a6ddb11980e9bc35aa289d051e36d1e69c66ecd0fe5f5406ff8ab91e3a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools_scm >=6.0
    # From setuptools_scm[toml]
    - tomli
  run:
    - python >={{ python_min }}
    - flake8
    - more-itertools

test:
  imports:
    - flake8_no_implicit_concat
  commands:
    - pip check
    - flake8 --version | grep no-implicit-concat
  requires:
    - flake8
    - pip
    - m2-grep  # [win]
    - python {{ python_min }}

about:
  home: https://github.com/10sr/flake8-no-implicit-concat
  summary: Flake8 plugin that forbids implicit str/bytes literal concatenations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
